### ISSUE TITLE
Module name conflict

### ISSUE THREAD

**Issue by robbrandt** [Portugao/Files#37]
Taking a look at this module again (since about 2015?).  I also use the "Files" module in the zikula-modules repository https://github.com/zikula-modules/Files so renaming one or the other will be necessary, at least for Zikula 1.3.

**Comment by Guite** [comment]
@Portugao works on a 1.5 version: https://github.com/Portugao/Files/tree/1.2.0

**Comment by Guite** [comment]
Also: the module was named `MUFiles` before... https://github.com/Portugao/Files/

So no name conflict!

**Comment by robbrandt** [comment]
Right, last time I looked at it, it was named MUFiles.  This afternoon I upgraded that old version to the 1.1 in the MUFiles folder and it worked fine (so far at least).

But my point is that both this module and https://github.com/zikula-modules/Files are now simply called "Files" and an unsuspecting user would install them both at modules/Files, which is not good.  I think one of them needs to be renamed.  I do hope the other Files module survives, as it is quite useful.

**Comment by Guite** [comment]
This repo is called `Files` and the full module name is `MU/FilesModule/`.
Similarly `Scribite` becomes `Zikula/ScribiteModule/` and so on...

**Comment by Guite** [comment]
> I do hope the other Files module survives, as it is quite useful.

You will need to adopt it if nobody else cares.

**Comment by Portugao** [comment]
Thx for your discussion. Closed.
